rm ../img/cam1/*.jpg
rm ../img/cam2/*.jpg
rm ../img/cam3/*.jpg
rm ../img/cam4/*.jpg
rm ../img/cam5/*.jpg
rm ../img/cam6/*.jpg
rm ../img/cam7/*.jpg
rm ../img/cam8/*.jpg
rm ../img/cam9/*.jpg
rm ../img/cam10/*.jpg
rm ../img/cam11/*.jpg
rm ../img/cam12/*.jpg
rm ../img/cam13/*.jpg
rm ../img/cam14/*.jpg
rm ../img/cam15/*.jpg
rm ../img/cam16/*.jpg
rm ../img/cam17/*.jpg
rm ../img/cam18/*.jpg